name: JimmyHits
favicon: null
layout_spectrum: 0.7535026560071856
typography_spectrum: 0.7341519633773714
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.861802602186799
  lightness: 0.47666513780131936
  saturation: 0.3096764865331352
  rhythmicContrast: 0.3345779119990766
purpose: []
